log_level: INFO

storage:
  storage_path: ./data/qdrant/storage
  snapshots_path: ./data/qdrant/snapshots

service:
  host: 127.0.0.1
  http_port: 6333
  grpc_port: 6334
  enable_cors: true

cluster:
  enabled: false

telemetry_disabled: true
